[package]
name = "graph"
version = "0.1.0"
authors = [
    "LucaCappelletti94 <cappelletti.luca94@gmail.com>",
    "Tommaso Fontana <tommaso.fontana.96@gmail.com>"    
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "graph"

[dev-dependencies]
linecount= "0.1.0"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
rayon = "1.1"
hashbrown = {version = "0.8", features = ["rayon", "inline-more"] }
rand = {version="0.7", features = ["small_rng"] }
itertools = "0.9.0"
permutation = "0.2.5"
counter = "0.5.2"
derive-getters = "0.1.0"
indicatif = {version = "0.15.0", features = ["rayon"]}
arbitrary = { version = "0.4.5", features = ["derive"] }
vec_rand = { git = "https://github.com/zommiommy/vec_rand", branch = "master" }

[build]
rustflags = ["-C target-cpu=native", "-C target-feature=-crt-static"]
target="x86_64-unknown-linux-musl"

[profile.release]
opt-level = 3
codgen-units=1
lto = "fat"
overflow-checks = false     # Disable integer overflow checks.
debug = false             # Include debug info.
debug-assertions = false  # Enables debug assertions.